# Generated by Django 3.2.3 on 2021-07-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade_origem', models.CharField(max_length=200)),
                ('cidade_destino', models.CharField(max_length=200)),
                ('distancia', models.IntegerField(blank=True)),
                ('long', models.CharField(max_length=200)),
                ('lati', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_rota', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('primeiro', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
