# Generated by Django 3.2.3 on 2021-07-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='sequecia',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
