# Generated by Django 3.2.3 on 2021-08-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0002_rota_sequecia'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='valor',
            field=models.CharField(default='aaaaaaaaaaaaa', max_length=200),
            preserve_default=False,
        ),
    ]
